### ISSUE TITLE
Github Installation Instructions

### ISSUE THREAD

**Issue by hemantmalik** [oracle/oraclejet#10]
`yo oraclejet <app name>`
leads to creation of a project that doesn't work as expected: the index.html served by grunt points to unreachable artifacts - alta css and others

`yo oraclejet <app name> --template=basic` [from the OTN get started page] works fine!

**Comment by peppertech** [comment]
If you run the grunt build command after the install, it will produce a /web directory with a working version of your app.  The proper CSS theme is added at build time depending on what --theme is defined.  The default is Alta, but you can include iOS, Android, or Windows.
