### ISSUE TITLE
Cannot build without themes folder (2.1.0)

### ISSUE THREAD

**Issue by gsavoie** [oracle/oraclejet#11]
Hi, just getting started with 2.1.0.

I noticed that after generating an oraclejet project we get this "themes" folder that include a copy of the alta theme. This folder is set on .gitignore so it is not checked in. When this folder is not there, we cannot launch grunt build... it throws the following:
>> Error: ENOENT: no such file or directory, stat 'C:\some\folder\project\themes\alta\web'

Even if I want to use a custom theme, the alta common copy part always fail.
>> Error: ENOENT: no such file or directory, stat 'C:\some\folder\project\themes\alta\common'

It makes sense that we don't need to push this folder as it should always get the latest from bower_components/oraclejet. Perhaps there is a bug or something missing in buildCommon.js#_copyThemeToStaging ?
I tried to add the folders manually to see if the stuff would be copied but it doesn't.

Easy steps to reproduce:
1. yo oraclejet myproject
2. delete myproject/themes folder (equivalent of freshly checking out the project)
3. grunt build

Let me know if I can give a hand!

**Comment by dongguader** [comment]
Hi,  the default theme from oracle, Alta, is required for the app to build. Please run "yo oraclejet:restore", which will generate the themes folder with the default Alta theme, plus install any missing dependencies.

**Comment by gsavoie** [comment]
Ok, for some reason I expected the folder to be put there at build time but I also noticed this morning that bowercopy was only called on oraclejet:restore so that also makes sense for the theme. 
I guess we can close this issue.
