### ISSUE TITLE
Enhancement: validation on key event

### ISSUE THREAD

**Issue by shimizust** [oracle/oraclejet#12]
Hi,

It seems JET input components only perform validation on a 'blur' event (e.g. tabbing out or clicking out). In some cases, however, validation on keypress (or other key event) provides a better user experience by giving instant feedback.

It would be great if we could just pass an option to the JET component indicating the event that triggers the validation. For example, you could pass a 'validateEvent' option:

```
 <input 
        id="username" 
        type="text"  
        data-bind="ojComponent: {
          component: 'ojInputText', 
          value: userName, 
          validators: [{
            type: 'regExp', 
            options: {
              pattern: '[a-zA-Z0-9]{3,}', 
              messageDetail: 'Enter at least 3 letters or numbers'}}],
          validateEvent: 'keypress'}">
```

Thanks for your consideration

**Comment by peppertech** [comment]
Hello,
This can be done today actually.  Please look at this example
http://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=passwordInput&demo=patternMatching
