### ISSUE TITLE
On model save, attributes params are not passed to validate

### ISSUE THREAD

**Issue by alex-michaud** [oracle/oraclejet#13]
I have ColorModel (oj.Model). In it I added a validate(**attributes**, **saveOptions**) method.

In my viewModel, I save my ColorModel like this : 
```
ColorModel.save(
                    {
                        'RGB': self.RGB()
                    },
                    {
                        patch: true,
                        wait: true
                    }
);
```

The date is sent to the backend properly.
But if I look into the validate method, the **attributes** is an empty object but I have my **saveOptions**.

Now, if I change my viewModel to save the ColorModel like this : 
```
ColorModel.set({ 'RGB': self.RGB() });
ColorModel.save(
                   {},
                    {
                        patch: true,
                        wait: true
                    }
);
```
The validate method is called with the attributes and the data is saved properly.

I think if we pass data to the save() method it should be sent to the attributes of the validate() method.

**Comment by blm7** [comment]
Hi,

Thanks for the report.  We'll file an issue and investigate a fix.

Thanks,

Ben

**Comment by brunoborges** [comment]
@blm7 has this been filled as an issue already in the real Oracle JET issue tracking system?

**Comment by blm7** [comment]
It has yes.
