### ISSUE TITLE
bower UNABLE_TO_GET_ISSUER_CERT_LOCALLY unable to get local issuer certificate

### ISSUE THREAD

**Issue by rajeshcse234** [oracle/oraclejet#20]
My Installation of NPM and other tools works fine and when i issue the command to create a project as below

yo oraclejet samplejet2 --template=navdrawer

command prompt will throw me the error 
"bower UNABLE_TO_GET_ISSUER_CERT_LOCALLY      Request to https://bower.herokuapp
com/packages/oraclejet failed: unable to get local issuer certificate
Error oraclejet samplejet2 --template=navdrawer gistry uri https://registry.n'

then once it finishes the command there will be no libs folder inside the js folder of my samplejet2 project

can one one help here how to solve this issue.

Regards
Rajesh

**Comment by peppertech** [comment]
This sounds like an issue with your Bower install.  Can you run a normal bower install of some library outside of the JET yeoman generator?  The generator is simply calling Bower to install some libraries. Nothing special happening.

**Comment by rajeshcse234** [comment]
I tried bower install jquery.
it fails with the same error 
bower UNABLE_TO_GET_ISSUER_CERT_LOCALLY      Request to https://bower.herokuapp.
com/packages/jquery failed: unable to get local issuer certificate

Can you please help.

Regards
Rajesh

**Comment by peppertech** [comment]
You're going to need to talk to the heroku folks about this one. It doesn't have anything to do with JET.  I don't have experience with apps on heroku myself, sorry.
