### ISSUE TITLE
Converting Date to ISO with Timezone

### ISSUE THREAD

**Issue by ankit-g-goyal** [oracle/oraclejet#21]
Currently the **oj.IntlConverterUtils** does not provide a way to convert a Date Object to timestamp as per my use-case I have to take users input as a Date and then pass it as a Timestamp to REST API.

**Comment by peppertech** [comment]
Hi Ankit,  

There really isn't any such thing as a timestamp in JavaScript.  This is not something that JET would provide. It's a basic functionality of JavaScript itself.  I recommend looking at something like this Stackoverflow thread to understand how to best get what would be considered a timestamp in JavaScript.
http://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript
