### ISSUE TITLE
Simple router example for browser refresh redirects to error page

### ISSUE THREAD

**Issue by guilsa** [oracle/oraclejet#22]
Simple router documentation in JET Cookbook says if you refresh the browser [1, 2], the proper state is restored in the page so the URL is bookmarkable. On browser refresh I get redirected to http://www.oracle.com/us/Error/index.html.

[1]. http://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=router&demo=simple
[2]. http://www.oracle.com/webfolder/technetwork/jet/demo/demo-router-simple.html?demoTheme=none&baseTheme=alta&formfactor=desktop

**Comment by peppertech** [comment]
The sample also discusses the issue of needing to have a URL rewrite rule setup on the server when you use the path adapter. We do not have that rewrite rule setup on the JET website (it's a long story as to why). If you switch to use the parameter adapter, it will work just fine.

**Comment by guilsa** [comment]
Awesome, thank you for letting us know.
