### ISSUE TITLE
grunt serve and build giving error

### ISSUE THREAD

**Issue by SahaAnirban** [oracle/oraclejet#31]
Hi,

grunt build and grunt serve are giving below error

$ grunt serve
Running "serve" task

Running "oraclejet-serve:undefined" (oraclejet-serve) task
 Oracle JET Grunt plugin
Processing Grunt command...
JET Warning: Missing platform. Default to web.
 Oracle JET Tooling
Fatal error: Error: ENOENT: no such file or directory, open 'C:\Users\del_Astle\MyApp\node_modules\oraclejet\package.json'

**Comment by SahaAnirban** [comment]
This issue is happening in 3.2.0 and with navBar template

**Comment by peppertech** [comment]
This is caused by a failed install with an error from a specific version of Node.  Try again with the latest version of JET and the latest LTS of Node.
