### ISSUE TITLE
ojet create jettest --template=navdrawer|navbar|basic|blank throws an error on OSX

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle/oraclejet#33]
Following this doc:
http://www.oracle.com/webfolder/technetwork/jet/globalGetStarted.html

and running on OSX:
`ojet create <project name> --template=navdrawer|navbar|basic|blank`

I get:

-bash: project: No such file or directory
-bash: navbar: command not found
-bash: basic: command not found
-bash: blank: command not found

**Comment by mikarinneoracle** [comment]
npm --version
3.10.3
node --version
v6.7.0

**Comment by geertjanw** [comment]
Those are options, e.g:

ojet create jettest --template=navdrawer

There you're using the navdrawer template.

ojet create jettest --template=navbar

There you're using the navbar template. Etc.

**Comment by mikarinneoracle** [comment]
Ahh.. I need to select one of these, I get it :)

**Comment by geertjanw** [comment]
Yup. Don't be greedy. :-)

**Comment by mikarinneoracle** [comment]
Allright :) many thanks!

**Comment by mikarinneoracle** [comment]
Very nice, it works :)

**Comment by blm7** [comment]
Hi,

Those are "or" options for the template.  Try

ojet create jettest --template=navdrawer

or

ojet create jettest --template=navbar


etc.

Ben

**Comment by aaabdelatti** [comment]
thank you

**Comment by mndileepraj** [comment]
d:\OJET>ojet create sampleapp --template=navdrawer
Processing template: navdrawer
Your app structure is generated. Continuing with library install.
(node:576) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
Error making request.
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80
    at ClientRequest.onError (d:\OJET\sampleapp\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:297:20)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN qunit-reporter-junit@1.1.1 requires a peer of qunitjs@* but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dmunired\AppData\Roaming\npm-cache\_logs\2019-08-22T18_16_25_879Z-debug.log

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

getting this error when i run the below command:

ojet create sample --template=navdrawer

when i run npm list -g --depth=0, my specs below:

d:\OJET>npm list -g --depth=0
C:\Users\dmunired\AppData\Roaming\npm
+-- @oracle/ojet-cli@7.1.0
+-- grunt-cli@1.3.2
`-- ojet-cli@3.2.0

**Comment by mndileepraj** [comment]
please help

**Comment by peppertech** [comment]
It would appear that you are behind a firewall.  Have you setup your npm
proxy configuration properly?

**Comment by peppertech** [comment]
It would appear that you are behind a firewall.  Have you setup your npm
proxy configuration properly? It also appears that you are using a very old
version of the JET CLI.
I'm going to guess that you installed it without using the @oracle org
prefix.

The proper installation command is
npm -g install @oracle/ojet-cli

**Comment by peppertech** [comment]
You may also want to remove that old version of the JET CLI just in case
there is some kind of conflict.
That ENOTFOUND 80 error is almost always a network issue though.
