### ISSUE TITLE
Don't JET4.1 support for IE browser ?

### ISSUE THREAD

**Issue by 1040003585** [oracle/oraclejet#34]
at title up.

**Comment by peppertech** [comment]
IE11 only.  Microsoft Edge is also supported.

**Comment by peppertech** [comment]
You can see the supported platforms in the FAQ on the JET website
http://www.oracle.com/webfolder/technetwork/jet/globalSupport-FAQ.html#platforms

**Comment by 1040003585** [comment]
OK, Thanks
