### ISSUE TITLE
oj-bind-for-each

### ISSUE THREAD

**Issue by schvepe** [oracle/oraclejet#35]
oj-bind-for-each not found  to parent  element <tr>,  this  template  print  values
     <script type="text/html" id="row_template">
             <oj-bind-for-each data='[{"type":"Apple"},{"type":"Orange"}]'>
              <template>
                <td><p><oj-bind-text value='[[$current.data.type]]'></oj-bind-text></p></td>
              </template>
              </oj-bind-for-each>
        </script>
but  the template below  no print  values, only difference is parent <tr>

     <script type="text/html" id="row_template">
        <tr>
             <oj-bind-for-each data='[{"type":"Apple"},{"type":"Orange"}]'>
              <template>
                <td><p><oj-bind-text value='[[$current.data.type]]'></oj-bind-text></p></td>
              </template>
              </oj-bind-for-each>
         <tr>
        </script>

**Comment by peppertech** [comment]
You should not include the TR element tag in your template.  The parent TR is generated for you as part of the row-template feature in the table
