### ISSUE TITLE
Display column header for the one identified as ID Attribute in oj-data-grid

### ISSUE THREAD

**Issue by sumeetdas** [oracle/oraclejet#36]
Is there a way to display column header for the ID attribute in oj-data-grid? Precisely, the top-left corner cell (whose id is "datagrid:corner") should have displayed the column header for ID attribute but remains blank. Currently, I'm using DOM API to display the column header but wonder if there's a better way to do that.

----------------------------------------------------------------
| [Missing Header]| Column Header 1 | Column Header 2 |
----------------------------------------------------------------
| Row Header 1      |
----------------------------------------------------------------
| Row Header 2      |
---------------------------------------------------------------

**Comment by peppertech** [comment]
Hi Sumeet,

For questions about functionality, it's best to post them in the Community Forum.
https://community.oracle.com/community/development_tools/oracle-jet/content

It's a pretty active community and a lot higher chance of getting your question answered in a timely manor.

Thanks
