### ISSUE TITLE
[BUG] oj-select-many  Placeholders duplicates

### ISSUE THREAD

**Issue by stanislav-web** [oracle/oraclejet#39]
Hello! 

**How to reproduce:**

1) When "oj-select-many" or "oj-combobox-many" has placeholder as native attribute and component attach "oj-listbox-search" because has a lot of values (30 -50)

2) Click to "oj-select-many" or "oj-select-combobox" and select nothing then click to empty area on the page

3) You can fill more then one placeholder in the "oj-select-many" or "oj-combobox-many" filed

![screenshot from 2018-04-17 17-14-23](https://user-images.githubusercontent.com/5216760/38875356-d8d65b70-4262-11e8-81d2-1602c57efd72.png)

**Comment by peppertech** [comment]
Can you please show a code snippet of how you have the HTML defined when this happens?  I can't seem to reproduce it in the Cookbook pages myself

**Comment by stanislav-web** [comment]
Sure! "oj-select-many" has this side-effect in the latest Chrome browser .  Firefox display ok

`
<div class="oj-flex-table">
    <div class="oj-flex-row thead columnSelector">
        <label class="oj-pointer">
            <input type="checkbox"
                   data-bind="checked: filterAll"> Select all
        </label>
    </div>
    <div class="oj-flex-row">
        <oj-select-many class="oj-su-filter-width"
                        placeholder="Find by company name"
                        value="{{filterCompaniesName}}"
                        disabled="[[filterDisable().name]]"
                        options="[[searchSuggestions().companyName()]]"
                        on-value-changed="[[companyNameSearchHandler]]">
        </oj-select-many>
    </div>
    <div class="oj-flex-row">
        <oj-select-many class="oj-su-filter-width"
                        placeholder="Find by short name"
                        value="{{filterCompaniesCard}}"
                        options="[[searchSuggestions().companyCard()]]"
                        on-value-changed="[[companyCardSearchHandler]]">
        </oj-select-many>
    </div>
    <div class="oj-flex-row">
        <oj-select-many class="oj-su-filter-width"
                        placeholder="Find by types"
                        value="{{filterTypes}}"
                        disabled="[[filterDisable().type]]"
                        options="[[searchSuggestions().companyType()]]"
                        on-value-changed="[[companyTypeSearchHandler]]">
        </oj-select-many>
    </div>
    <div class="oj-flex-row">
        <oj-select-many class="oj-su-filter-width"
                        placeholder="Find by VPN types"
                        value="{{filterVpnTypes}}"
                        disabled="[[filterDisable().vpn]]"
                        options="[[searchSuggestions().companyVpnType()]]"
                        on-value-changed="[[companyVpnTypeSearchHandler]]">
        </oj-select-many>
    </div>
</div>
`

**Comment by peppertech** [comment]
Thanks, this looks like it may have been copied out of the code that is generated by some other JET component like oj-data-grid maybe?  Are you trying to add oj-select-many into a DataGrid component in some way.  If you just copy and paste the code that you've provided above (replacing variables with static values) it all works when I drop it into an oj-select-many Cookbook page.

Is there more to this code than what you've provided?

Are there any error messages in the browser console when you see this happen?

**Comment by stanislav-web** [comment]
Hi , again! 
Tell me,  please are there any ideas for eliminating this error? Or some of alternate solutions

**Comment by peppertech** [comment]
I can't reproduce the issue.  Are you an Oracle employee by chance?  If you are, please contact me via email and let's take this offline.  If not, I'll have to work out a way to reproduce the issue some other way.

**Comment by stanislav-web** [comment]
Yes exactly. I just make an update  Ojet  to latest  5.0.0 and the problem has gone.
Currently, I can not completely migrate from v4.2.0, but I'll keep in mind!
Thanks, I'm sorry for the trouble.
