### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by timqian** [oracle/oraclejet#4]
Besides
```
npm -g install yo 
npm -g install grunt 
npm -g install generator-oraclejet
```
You also need to install `bower` and `grunt-cli` in order to run  
`yo oraclejet <project name> --template=basic`
 successfully.

This is untold in the README.md or get started page(http://www.oracle.com/webfolder/technetwork/jet/globalGetStarted.html)

system: OS X Yosemite 10.10.5
node version: 5.0.0
npm version: 3.3.10

**Comment by peppertech** [comment]
Hi Timqian, 

Thanks for reporting your issues.  We've updated the website and will have the README here in github updated shortly.

**Comment by guilsa** [comment]
After installing ```bower``` and ```grunt-cli``` I get bower errors during installation on El Capitan and Ubuntu 16. Also tried running ```brew update``` and ```brew doctor``` on Mac.

> Writing  oraclejetconfig.json
> Invoking grunt bowercopy.
> Oracle JET: No config file...writing the default config...
> Loading "Gruntfile.js" tasks...ERROR
> >> Error: Unable to read "bower_components/oraclejet/bower.json" file (Error code: ENOENT).
> >> No "bowercopy" targets found.
> Warning: Task "bowercopy" failed. Use --force to continue.
> 
> Aborted due to warnings.
> Error oraclejet web-app-basic --template=basic
> 
> Oracle JET Error: (during Invoking grunt bowercopy.) 3

**Comment by peppertech** [comment]
Hi guilsa,

This is most likely caused by permission issues on the Mac.  Please read the [Developers Guide](https://docs.oracle.com/middleware/jet202/jet/developer/GUID-ABE2373F-287F-4C3A-BEBD-02F179F399FD.htm#JETDG-GUID-C8D97F89-552F-437B-8DC1-6A92CCC196DB) on possible solutions using "sudo" when installing on a Mac.
