### ISSUE TITLE
table source does not allow 'hasOwnProperty' as column name

### ISSUE THREAD

**Issue by xsh525** [oracle/oraclejet#42]
If set the table source has a column named "hasOwnProperty", it goes wrong. Looks like the 'hasOwnProperty' function is used for rows but in this case this function(From Object) is hidden. 
Two ways may solve this issue: Use Object.create(null)  to construct rows then use 'in' to iterate, or use Object.hasOwnProperty instead.

**Comment by hbroek** [comment]
Hi, sorry for the delay. Thanks for reporting this issue, we logged an internal issue for it and will address it in a future release.

**Comment by hbroek** [comment]
After reviewing the issue it turns out to be resolved in JET 6.0.0
