### ISSUE TITLE
Runtime code build

### ISSUE THREAD

**Issue by franciscoAlves27** [oracle/oraclejet#44]
Hello i didn't found any place.

oj.Core have some feature to compile/build code in runtime ?
I have this self.html with that code bellow and trying to put him,
but the component donst generate the _input_ element inside the _oj-input-text_;

>  var divHTml = document.getElementById("divHtmlGerado");
                    divHTml.innerHTML = self.html

> <div> 
            <oj-label show-required="true">Password</oj-label>
            <oj-input-text id="ATTRIBUTE_PASSWORD" name="ATTRIBUTE_PASSWORD"  placeholder="password" ="password" data-bind="textInput: self.PASSWORD"  required="true"></oj-input-text>
</div>'

**Comment by peppertech** [comment]
Hi Francisco,

Take a look at this jsFiddle for how to load elements dynamically.  https://jsfiddle.net/peppertech/ps1hy4x7/

If you wanted to load something from an external HTML file (not recommended for security reasons) you would use the Requirejs Text plugin to load the .html file first, and then reference that content.

**Comment by franciscoAlves27** [comment]
Hi John, i was trying to render a whole html string into the page. 
The code is generated by a application separated.
I have a system in angularJS with the same logic, bellow, i am trying to recreate a similar system but in oracle jet.


> var compiledElement = $compile(entidade.html)($scope);
  pageElement.append(compiledElement);

**Comment by peppertech** [comment]
I've found the appropriate approach when dealing with dynamic elements.  Using the applyBindings call.  However it sounds like you have a much larger HTML section that you are adding.  I would take a closer look at the oj-module element that is available to you in JET.  You can define the view and the viewModel dynamically and it will handle the bindings for you.  It also has it's own lifecycle methods so you can have far more control over what gets loaded when.

http://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=ModuleElement&demo=simple

**Comment by franciscoAlves27** [comment]
Thank you very much, i going to have a look!
