### ISSUE TITLE
OJET Tab Bar delete key focus problem

### ISSUE THREAD

**Issue by carmacleod** [oracle/oraclejet#48]
Chrome browser:
On the [Tab Bar "Add and Remove" page](https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=tabbar&demo=tbaddremovetabs) if you use the keyboard Delete key to delete the "Security" tab, then focus does not return to any other Tab and you need to use the mouse to give focus to one of the tabs again.
Firefox:
As above, except that deleting any tab with the Delete key causes Tab Bar focus to be completely lost until the next mouse click. (i.e. always need to set tabindex="0" on another tab, but that is not happening after Delete)

**Comment by peppertech** [comment]
Thanks for pointing this out.  I'll file a bug internally and we'll get it looked at right away.

**Comment by peppertech** [comment]
This appears to be working correctly with the most recent release (v8.2.0 as of this writing).  Please re-open if you are still seeing issues.
