### ISSUE TITLE
future-proof choice

### ISSUE THREAD

**Issue by rand99** [oracle/oraclejet#50]
will oracle jet continue to exist?

sry, but i think about using oracle jet for a project and heard about people got let go in the cloud sector

**Comment by peppertech** [comment]
JET is currently used by over 100 commercial products from Oracle and continues to grow rapidly within the larger Oracle partner and customer ecosystem.  Take a look at the Success Stories page on the main JET website for some of the larger consulting firms from around the world that are using JET today.  http://oraclejet.org

**Comment by rand99** [comment]
Thank you. 
Of what i tested jet works really great.
