### ISSUE TITLE
Getting "Access denied" when running example

### ISSUE THREAD

**Issue by ashi-sh** [oracle/oraclejet#55]
When running example given at http://www.oracle.com/pls/topic/lookup?ctx=jet800&id=homepage

I have getting this error in web browser.

Screenshot attached.
https://paste.pics/49824031876975ba08a4883ff8c24a2e
https://paste.pics/0a5ba696d1922a96cb0b1fa564359e1e

**Comment by ashi-sh** [comment]
oraclejet is not releasing port 8000 even after killing the process after finding using command.
$ netstat -tulnap|grep 8000

Any pointers?

**Comment by peppertech** [comment]
Are you sure that something else isn't using port 8000?  How did you
install the application that you are trying to run?
What operating system is this on and what version of JET are you working
with?

**Comment by ashi-sh** [comment]
Installed it through ubuntu (19.10) command line
Oracle JET Command Line Interface, version: 8.0.0
"Access denied" is persistent.

**Comment by peppertech** [comment]
Hi Ashish,

Did you use sudo when you did the initial installation of the JET CLI?  I
haven't seen this specific issue before and we have a lot of developers
running on Linux so I'm suspecting this is an issue with your specific
environment.  Can you tell me what version of Nodejs, and NPM you have
installed as well?

Thanks

**Comment by ashi-sh** [comment]
Hi,
I used "sudo" and everything seems to work with it. Thanks, peppertech! It worked!
