### ISSUE TITLE
<oj-buttonset-one> component's solid chroming fails to render

### ISSUE THREAD

**Issue by pentzzsolt** [oracle/oraclejet#65]
Setting the `chroming` property to `solid` on `<oj-buttonset-one>` makes the entire component invisible, although, there aren't any errors thrown.
The `solid` value for the `chroming` property is listed as a valid value [in the documentation](https://docs.oracle.com/en/middleware/developer-tools/jet/9/reference-api/oj.ojButtonsetOne.html#chroming) and is also present in the `ojButtonsetOneSettableProperties` interface.
It appears the `.oj-buttonset.oj-button-full-chrome` selector has `visibility: hidden;` applied in `redwood.css:9129`.

**Comment by peppertech** [comment]
From the API docs for the solid option:
Solid buttons stand out, and direct the user's attention to the most important actions in the UI. **Note that this option is not supported in the Redwood theme.**

**Comment by pentzzsolt** [comment]
Indeed. My bad!
