### ISSUE TITLE
oj-navigation-list with CoreRouter

### ISSUE THREAD

**Issue by wrushasendakhane** [oracle/oraclejet#66]
I have
let routes = [/*All the routes of the application defined here*/]
let navData = [/*dynamic as it changes based on functionality*/]
Within the application I have to update the navigation list.
so I have observable nvaDaraProvider to feed the changes.
But, this.selection = new KnockoutRouterAdapter(self.router);
![CoreRouter - Error](https://user-images.githubusercontent.com/2119851/87718272-49fb0280-c766-11ea-9cc9-8d386b354861.PNG)

do not reflect on the tab, it retains the tab position which was last selected.

I see that in appController.js, this.selection.path() is set correctly but the highlight is showing the last selected position

**Comment by bhalke** [comment]
Hi wrushasendakhane , 

Sorry, I'm not clear with query, but I assume you are trying to set selection on navigation tab, so you can set the selection as below. 

`this.selection('item');`

You can refer this example for more clarity, https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=navigationbar&demo=nbUsingArrayDataProvider

If you require any further information, let me know

Thank you
Siddesh

**Comment by wrushasendakhane** [comment]
I am using oj-navigation-list with CoreRouter
with selection={{selection.path}}

this.selection = new KnockoutRouterAdapter(router);

and I have to dynamically modify the navDataProvider,

When I debug I see the selection.path holds correct value but display do not highlight the correct tab.

**Comment by itlgit** [comment]
Can you paste a code sample that's dynamically updating the navDataProvider?

**Comment by wrushasendakhane** [comment]
https://github.com/wrushasendakhane/CoreRouterWithNavbar

Created a simple project,

From Customers Page -> Go Inside
It will take into new list of navDataProvider
Change from Dashboard to About
Click "Go Back"
It will take back to Customers Page
Now Again click "Go Inside"
It routes to "Dashboard" but Navbar is still highlighting "About"

**Comment by wrushasendakhane** [comment]
> Can you paste a code sample that's dynamically updating the navDataProvider?

https://github.com/wrushasendakhane/CoreRouterWithNavbar

Created a simple project,

From Customers Page -> Go Inside
It will take into new list of navDataProvider
Change from Dashboard to About
Click "Go Back"
It will take back to Customers Page
Now Again click "Go Inside"
It routes to "Dashboard" but Navbar is still highlighting "About"

**Comment by wrushasendakhane** [comment]
There is a issue in oj-navigation-list component but got the workaround for now on the community thread.

this.gotoRoute = (route) => {
      **var navList = document.getElementById("navList");
      navList.setProperty("selection", route);**
      router.go({ path: route });
    };
