### ISSUE TITLE
Text Area is not resizing correctly, even in the CookBook (OracleJet 9.2)

### ISSUE THREAD

**Issue by senamaud** [oracle/oraclejet#71]
The `Text Area` is not resizing correctly. Tested with `Firefox 82.0.3` and `Chrome 86.0.4240.193 (Official Build) (64-bit)`

OJ 9.2 https://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=textArea&demo=resize

OJ 8.3 https://www.oracle.com/webfolder/technetwork/jet-830/jetCookbook.html?component=textArea&demo=resize

**Comment by peppertech** [comment]
This is a known issue and will be fixed in the v10 release in January.

**Comment by senamaud** [comment]
Thanks!
