### ISSUE TITLE
Bug: Swiping two times on the same ListView item makes the underlying button disappear

### ISSUE THREAD

**Issue by janis-kra** [oracle/oraclejet#8]
Hi there, 

we encountered a bug on our ListView items, which have a slide-to-reveal button associated with them: Whenever you swipe two times on the same item, the button disappears (and cannot be clicked anymore), but the item is still indented as if the button was still there. Swiping a third time makes the button appear again.

This behavior can be reproduced on the [Swipe To Reveal Cookbook Example](http://www.oracle.com/webfolder/technetwork/jet/uiComponents-swipeToReveal-basicSwipeToReveal.html) by doing a swipe to the right, two times consecutively on the same element:

First swipe:
<img width="296" alt="screen shot 2016-05-14 at 14 32 25" src="https://cloud.githubusercontent.com/assets/8240324/15268495/ddb381a6-19e0-11e6-9b61-dd764ab96392.png">

Second swipe:
<img width="303" alt="screen shot 2016-05-14 at 14 32 37" src="https://cloud.githubusercontent.com/assets/8240324/15268496/ddb4784a-19e0-11e6-8c31-33e86a36a88b.png">

**Comment by peppertech** [comment]
Thanks for reporting this, we'll look into it right away and try to get a fix in for the next release.  If I can get a workaround, I'll post it up here.

**Comment by peppertech** [comment]
Janis,  I'm no longer able to reproduce this in the latest release of JET. http://www.oracle.com/webfolder/technetwork/jet/jetCookbook.html?component=swipeToReveal&demo=basicSwipeToReveal

Are you able to reproduce on your end still?  If not, please go ahead and close the issue.

**Comment by janis-kra** [comment]
@peppertech seems to be resolved in 2.2, thanks
